/*
TiDB Cloud Dedicated Import API

TiDB Cloud Dedicated Import API (subset of the TiDB Cloud Dedicated API, generated from tidbcloud-oas-v1beta1-dedicated.swagger.json)

API version: v1beta1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package imp

import (
	"encoding/json"
)

// checks if the V1beta1ListImportsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1beta1ListImportsResponse{}

// V1beta1ListImportsResponse The response message for listing imports.
type V1beta1ListImportsResponse struct {
	// The list of import tasks.
	Imports []V1beta1Import `json:"imports,omitempty"`
	// The total number of import tasks.
	TotalSize *int32 `json:"totalSize,omitempty"`
	// The token to retrieve the next page of results. Use this value as the `pageToken` parameter in the next request. This field is empty when there are no more pages.
	NextPageToken *string `json:"nextPageToken,omitempty"`
}

// NewV1beta1ListImportsResponse instantiates a new V1beta1ListImportsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1beta1ListImportsResponse() *V1beta1ListImportsResponse {
	this := V1beta1ListImportsResponse{}
	return &this
}

// NewV1beta1ListImportsResponseWithDefaults instantiates a new V1beta1ListImportsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1beta1ListImportsResponseWithDefaults() *V1beta1ListImportsResponse {
	this := V1beta1ListImportsResponse{}
	return &this
}

// GetImports returns the Imports field value if set, zero value otherwise.
func (o *V1beta1ListImportsResponse) GetImports() []V1beta1Import {
	if o == nil || IsNil(o.Imports) {
		var ret []V1beta1Import
		return ret
	}
	return o.Imports
}

// GetImportsOk returns a tuple with the Imports field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1beta1ListImportsResponse) GetImportsOk() ([]V1beta1Import, bool) {
	if o == nil || IsNil(o.Imports) {
		return nil, false
	}
	return o.Imports, true
}

// HasImports returns a boolean if a field has been set.
func (o *V1beta1ListImportsResponse) HasImports() bool {
	if o != nil && !IsNil(o.Imports) {
		return true
	}

	return false
}

// SetImports gets a reference to the given []V1beta1Import and assigns it to the Imports field.
func (o *V1beta1ListImportsResponse) SetImports(v []V1beta1Import) {
	o.Imports = v
}

// GetTotalSize returns the TotalSize field value if set, zero value otherwise.
func (o *V1beta1ListImportsResponse) GetTotalSize() int32 {
	if o == nil || IsNil(o.TotalSize) {
		var ret int32
		return ret
	}
	return *o.TotalSize
}

// GetTotalSizeOk returns a tuple with the TotalSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1beta1ListImportsResponse) GetTotalSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalSize) {
		return nil, false
	}
	return o.TotalSize, true
}

// HasTotalSize returns a boolean if a field has been set.
func (o *V1beta1ListImportsResponse) HasTotalSize() bool {
	if o != nil && !IsNil(o.TotalSize) {
		return true
	}

	return false
}

// SetTotalSize gets a reference to the given int32 and assigns it to the TotalSize field.
func (o *V1beta1ListImportsResponse) SetTotalSize(v int32) {
	o.TotalSize = &v
}

// GetNextPageToken returns the NextPageToken field value if set, zero value otherwise.
func (o *V1beta1ListImportsResponse) GetNextPageToken() string {
	if o == nil || IsNil(o.NextPageToken) {
		var ret string
		return ret
	}
	return *o.NextPageToken
}

// GetNextPageTokenOk returns a tuple with the NextPageToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1beta1ListImportsResponse) GetNextPageTokenOk() (*string, bool) {
	if o == nil || IsNil(o.NextPageToken) {
		return nil, false
	}
	return o.NextPageToken, true
}

// HasNextPageToken returns a boolean if a field has been set.
func (o *V1beta1ListImportsResponse) HasNextPageToken() bool {
	if o != nil && !IsNil(o.NextPageToken) {
		return true
	}

	return false
}

// SetNextPageToken gets a reference to the given string and assigns it to the NextPageToken field.
func (o *V1beta1ListImportsResponse) SetNextPageToken(v string) {
	o.NextPageToken = &v
}

func (o V1beta1ListImportsResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1beta1ListImportsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Imports) {
		toSerialize["imports"] = o.Imports
	}
	if !IsNil(o.TotalSize) {
		toSerialize["totalSize"] = o.TotalSize
	}
	if !IsNil(o.NextPageToken) {
		toSerialize["nextPageToken"] = o.NextPageToken
	}
	return toSerialize, nil
}

type NullableV1beta1ListImportsResponse struct {
	value *V1beta1ListImportsResponse
	isSet bool
}

func (v NullableV1beta1ListImportsResponse) Get() *V1beta1ListImportsResponse {
	return v.value
}

func (v *NullableV1beta1ListImportsResponse) Set(val *V1beta1ListImportsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV1beta1ListImportsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV1beta1ListImportsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1beta1ListImportsResponse(val *V1beta1ListImportsResponse) *NullableV1beta1ListImportsResponse {
	return &NullableV1beta1ListImportsResponse{value: val, isSet: true}
}

func (v NullableV1beta1ListImportsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1beta1ListImportsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
