/*
TiDB Cloud Dedicated Import API

TiDB Cloud Dedicated Import API (subset of the TiDB Cloud Dedicated API, generated from tidbcloud-oas-v1beta1-dedicated.swagger.json)

API version: v1beta1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package imp

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the V1beta1Import type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1beta1Import{}

// V1beta1Import The import.
type V1beta1Import struct {
	// The name of the import task, in the format of `clusters/{cluster_id}/imports/{import_id}`.
	Name *string `json:"name,omitempty"`
	// The ID of the target cluster for the import.
	ClusterId *string `json:"clusterId,omitempty"`
	// The total size of the data to be imported, in bytes.
	TotalSize *string `json:"totalSize,omitempty"`
	// The timestamp when the import task was created, in the [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
	CreateTime *time.Time `json:"createTime,omitempty"`
	// The timestamp when the import task was completed, in the [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
	CompleteTime *time.Time `json:"completeTime,omitempty"`
	// The state of the import task.
	State *V1beta1ImportStateEnum `json:"state,omitempty"`
	// The percentage of import progress, excluding post-processing.
	CompletePercent *int32 `json:"completePercent,omitempty"`
	// An error message if the import task failed. Otherwise, empty.
	Message *string `json:"message,omitempty"`
	// The email address of the user who create the import task.
	Creator *string `json:"creator,omitempty"`
	// The additional details about how the import task is created.
	CreationDetails V1beta1CreationDetails `json:"creationDetails"`
	// The unique identifier of the import task.
	ImportId *string `json:"importId,omitempty"`
}

type _V1beta1Import V1beta1Import

// NewV1beta1Import instantiates a new V1beta1Import object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1beta1Import(creationDetails V1beta1CreationDetails) *V1beta1Import {
	this := V1beta1Import{}
	this.CreationDetails = creationDetails
	return &this
}

// NewV1beta1ImportWithDefaults instantiates a new V1beta1Import object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1beta1ImportWithDefaults() *V1beta1Import {
	this := V1beta1Import{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *V1beta1Import) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1beta1Import) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *V1beta1Import) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *V1beta1Import) SetName(v string) {
	o.Name = &v
}

// GetClusterId returns the ClusterId field value if set, zero value otherwise.
func (o *V1beta1Import) GetClusterId() string {
	if o == nil || IsNil(o.ClusterId) {
		var ret string
		return ret
	}
	return *o.ClusterId
}

// GetClusterIdOk returns a tuple with the ClusterId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1beta1Import) GetClusterIdOk() (*string, bool) {
	if o == nil || IsNil(o.ClusterId) {
		return nil, false
	}
	return o.ClusterId, true
}

// HasClusterId returns a boolean if a field has been set.
func (o *V1beta1Import) HasClusterId() bool {
	if o != nil && !IsNil(o.ClusterId) {
		return true
	}

	return false
}

// SetClusterId gets a reference to the given string and assigns it to the ClusterId field.
func (o *V1beta1Import) SetClusterId(v string) {
	o.ClusterId = &v
}

// GetTotalSize returns the TotalSize field value if set, zero value otherwise.
func (o *V1beta1Import) GetTotalSize() string {
	if o == nil || IsNil(o.TotalSize) {
		var ret string
		return ret
	}
	return *o.TotalSize
}

// GetTotalSizeOk returns a tuple with the TotalSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1beta1Import) GetTotalSizeOk() (*string, bool) {
	if o == nil || IsNil(o.TotalSize) {
		return nil, false
	}
	return o.TotalSize, true
}

// HasTotalSize returns a boolean if a field has been set.
func (o *V1beta1Import) HasTotalSize() bool {
	if o != nil && !IsNil(o.TotalSize) {
		return true
	}

	return false
}

// SetTotalSize gets a reference to the given string and assigns it to the TotalSize field.
func (o *V1beta1Import) SetTotalSize(v string) {
	o.TotalSize = &v
}

// GetCreateTime returns the CreateTime field value if set, zero value otherwise.
func (o *V1beta1Import) GetCreateTime() time.Time {
	if o == nil || IsNil(o.CreateTime) {
		var ret time.Time
		return ret
	}
	return *o.CreateTime
}

// GetCreateTimeOk returns a tuple with the CreateTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1beta1Import) GetCreateTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreateTime) {
		return nil, false
	}
	return o.CreateTime, true
}

// HasCreateTime returns a boolean if a field has been set.
func (o *V1beta1Import) HasCreateTime() bool {
	if o != nil && !IsNil(o.CreateTime) {
		return true
	}

	return false
}

// SetCreateTime gets a reference to the given time.Time and assigns it to the CreateTime field.
func (o *V1beta1Import) SetCreateTime(v time.Time) {
	o.CreateTime = &v
}

// GetCompleteTime returns the CompleteTime field value if set, zero value otherwise.
func (o *V1beta1Import) GetCompleteTime() time.Time {
	if o == nil || IsNil(o.CompleteTime) {
		var ret time.Time
		return ret
	}
	return *o.CompleteTime
}

// GetCompleteTimeOk returns a tuple with the CompleteTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1beta1Import) GetCompleteTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CompleteTime) {
		return nil, false
	}
	return o.CompleteTime, true
}

// HasCompleteTime returns a boolean if a field has been set.
func (o *V1beta1Import) HasCompleteTime() bool {
	if o != nil && !IsNil(o.CompleteTime) {
		return true
	}

	return false
}

// SetCompleteTime gets a reference to the given time.Time and assigns it to the CompleteTime field.
func (o *V1beta1Import) SetCompleteTime(v time.Time) {
	o.CompleteTime = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *V1beta1Import) GetState() V1beta1ImportStateEnum {
	if o == nil || IsNil(o.State) {
		var ret V1beta1ImportStateEnum
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1beta1Import) GetStateOk() (*V1beta1ImportStateEnum, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *V1beta1Import) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given V1beta1ImportStateEnum and assigns it to the State field.
func (o *V1beta1Import) SetState(v V1beta1ImportStateEnum) {
	o.State = &v
}

// GetCompletePercent returns the CompletePercent field value if set, zero value otherwise.
func (o *V1beta1Import) GetCompletePercent() int32 {
	if o == nil || IsNil(o.CompletePercent) {
		var ret int32
		return ret
	}
	return *o.CompletePercent
}

// GetCompletePercentOk returns a tuple with the CompletePercent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1beta1Import) GetCompletePercentOk() (*int32, bool) {
	if o == nil || IsNil(o.CompletePercent) {
		return nil, false
	}
	return o.CompletePercent, true
}

// HasCompletePercent returns a boolean if a field has been set.
func (o *V1beta1Import) HasCompletePercent() bool {
	if o != nil && !IsNil(o.CompletePercent) {
		return true
	}

	return false
}

// SetCompletePercent gets a reference to the given int32 and assigns it to the CompletePercent field.
func (o *V1beta1Import) SetCompletePercent(v int32) {
	o.CompletePercent = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *V1beta1Import) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1beta1Import) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *V1beta1Import) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *V1beta1Import) SetMessage(v string) {
	o.Message = &v
}

// GetCreator returns the Creator field value if set, zero value otherwise.
func (o *V1beta1Import) GetCreator() string {
	if o == nil || IsNil(o.Creator) {
		var ret string
		return ret
	}
	return *o.Creator
}

// GetCreatorOk returns a tuple with the Creator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1beta1Import) GetCreatorOk() (*string, bool) {
	if o == nil || IsNil(o.Creator) {
		return nil, false
	}
	return o.Creator, true
}

// HasCreator returns a boolean if a field has been set.
func (o *V1beta1Import) HasCreator() bool {
	if o != nil && !IsNil(o.Creator) {
		return true
	}

	return false
}

// SetCreator gets a reference to the given string and assigns it to the Creator field.
func (o *V1beta1Import) SetCreator(v string) {
	o.Creator = &v
}

// GetCreationDetails returns the CreationDetails field value
func (o *V1beta1Import) GetCreationDetails() V1beta1CreationDetails {
	if o == nil {
		var ret V1beta1CreationDetails
		return ret
	}

	return o.CreationDetails
}

// GetCreationDetailsOk returns a tuple with the CreationDetails field value
// and a boolean to check if the value has been set.
func (o *V1beta1Import) GetCreationDetailsOk() (*V1beta1CreationDetails, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreationDetails, true
}

// SetCreationDetails sets field value
func (o *V1beta1Import) SetCreationDetails(v V1beta1CreationDetails) {
	o.CreationDetails = v
}

// GetImportId returns the ImportId field value if set, zero value otherwise.
func (o *V1beta1Import) GetImportId() string {
	if o == nil || IsNil(o.ImportId) {
		var ret string
		return ret
	}
	return *o.ImportId
}

// GetImportIdOk returns a tuple with the ImportId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1beta1Import) GetImportIdOk() (*string, bool) {
	if o == nil || IsNil(o.ImportId) {
		return nil, false
	}
	return o.ImportId, true
}

// HasImportId returns a boolean if a field has been set.
func (o *V1beta1Import) HasImportId() bool {
	if o != nil && !IsNil(o.ImportId) {
		return true
	}

	return false
}

// SetImportId gets a reference to the given string and assigns it to the ImportId field.
func (o *V1beta1Import) SetImportId(v string) {
	o.ImportId = &v
}

func (o V1beta1Import) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1beta1Import) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.ClusterId) {
		toSerialize["clusterId"] = o.ClusterId
	}
	if !IsNil(o.TotalSize) {
		toSerialize["totalSize"] = o.TotalSize
	}
	if !IsNil(o.CreateTime) {
		toSerialize["createTime"] = o.CreateTime
	}
	if !IsNil(o.CompleteTime) {
		toSerialize["completeTime"] = o.CompleteTime
	}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	if !IsNil(o.CompletePercent) {
		toSerialize["completePercent"] = o.CompletePercent
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Creator) {
		toSerialize["creator"] = o.Creator
	}
	toSerialize["creationDetails"] = o.CreationDetails
	if !IsNil(o.ImportId) {
		toSerialize["importId"] = o.ImportId
	}
	return toSerialize, nil
}

func (o *V1beta1Import) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"creationDetails",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV1beta1Import := _V1beta1Import{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV1beta1Import)

	if err != nil {
		return err
	}

	*o = V1beta1Import(varV1beta1Import)

	return err
}

type NullableV1beta1Import struct {
	value *V1beta1Import
	isSet bool
}

func (v NullableV1beta1Import) Get() *V1beta1Import {
	return v.value
}

func (v *NullableV1beta1Import) Set(val *V1beta1Import) {
	v.value = val
	v.isSet = true
}

func (v NullableV1beta1Import) IsSet() bool {
	return v.isSet
}

func (v *NullableV1beta1Import) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1beta1Import(val *V1beta1Import) *NullableV1beta1Import {
	return &NullableV1beta1Import{value: val, isSet: true}
}

func (v NullableV1beta1Import) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1beta1Import) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
