/*
TiDB Cloud Dedicated Import API

TiDB Cloud Dedicated Import API (subset of the TiDB Cloud Dedicated API, generated from tidbcloud-oas-v1beta1-dedicated.swagger.json)

API version: v1beta1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package imp

import (
	"encoding/json"
	"fmt"
)

// V1beta1ImportValidationItem The validation item of the import.   - IMPORT_VALIDATION_ITEM_UNSPECIFIED: The validation item is unspecified.  - SOURCE_ACCESS_CHECK: The validation item is source access check.  - TARGET_ACCESS_CHECK: The validation item is target access check.(deprecated)  - FILTER_AND_RULE_CHECK: The validation item is filter and rule check.(deprecated)  - IMPORT_PRECHECK: The validation item is import precheck.  - TARGET_TABLE_EMPTY_CHECK: The validation item is target table empty check.  - ESTIMATE_SIZE: The validation item is estimate size.(deprecated)  - IMPORT_DATA_ONLY_CHECK: The validation item is import data only check.
type V1beta1ImportValidationItem string

// List of v1beta1ImportValidationItem
const (
	V1BETA1IMPORTVALIDATIONITEM_IMPORT_VALIDATION_ITEM_UNSPECIFIED V1beta1ImportValidationItem = "IMPORT_VALIDATION_ITEM_UNSPECIFIED"
	V1BETA1IMPORTVALIDATIONITEM_SOURCE_ACCESS_CHECK                V1beta1ImportValidationItem = "SOURCE_ACCESS_CHECK"
	V1BETA1IMPORTVALIDATIONITEM_TARGET_ACCESS_CHECK                V1beta1ImportValidationItem = "TARGET_ACCESS_CHECK"
	V1BETA1IMPORTVALIDATIONITEM_FILTER_AND_RULE_CHECK              V1beta1ImportValidationItem = "FILTER_AND_RULE_CHECK"
	V1BETA1IMPORTVALIDATIONITEM_IMPORT_PRECHECK                    V1beta1ImportValidationItem = "IMPORT_PRECHECK"
	V1BETA1IMPORTVALIDATIONITEM_TARGET_TABLE_EMPTY_CHECK           V1beta1ImportValidationItem = "TARGET_TABLE_EMPTY_CHECK"
	V1BETA1IMPORTVALIDATIONITEM_ESTIMATE_SIZE                      V1beta1ImportValidationItem = "ESTIMATE_SIZE"
	V1BETA1IMPORTVALIDATIONITEM_IMPORT_DATA_ONLY_CHECK             V1beta1ImportValidationItem = "IMPORT_DATA_ONLY_CHECK"
)

// All allowed values of V1beta1ImportValidationItem enum
var AllowedV1beta1ImportValidationItemEnumValues = []V1beta1ImportValidationItem{
	"IMPORT_VALIDATION_ITEM_UNSPECIFIED",
	"SOURCE_ACCESS_CHECK",
	"TARGET_ACCESS_CHECK",
	"FILTER_AND_RULE_CHECK",
	"IMPORT_PRECHECK",
	"TARGET_TABLE_EMPTY_CHECK",
	"ESTIMATE_SIZE",
	"IMPORT_DATA_ONLY_CHECK",
}

func (v *V1beta1ImportValidationItem) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := V1beta1ImportValidationItem(value)
	for _, existing := range AllowedV1beta1ImportValidationItemEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid V1beta1ImportValidationItem", value)
}

// NewV1beta1ImportValidationItemFromValue returns a pointer to a valid V1beta1ImportValidationItem
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewV1beta1ImportValidationItemFromValue(v string) (*V1beta1ImportValidationItem, error) {
	ev := V1beta1ImportValidationItem(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for V1beta1ImportValidationItem: valid values are %v", v, AllowedV1beta1ImportValidationItemEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v V1beta1ImportValidationItem) IsValid() bool {
	for _, existing := range AllowedV1beta1ImportValidationItemEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to v1beta1ImportValidationItem value
func (v V1beta1ImportValidationItem) Ptr() *V1beta1ImportValidationItem {
	return &v
}

type NullableV1beta1ImportValidationItem struct {
	value *V1beta1ImportValidationItem
	isSet bool
}

func (v NullableV1beta1ImportValidationItem) Get() *V1beta1ImportValidationItem {
	return v.value
}

func (v *NullableV1beta1ImportValidationItem) Set(val *V1beta1ImportValidationItem) {
	v.value = val
	v.isSet = true
}

func (v NullableV1beta1ImportValidationItem) IsSet() bool {
	return v.isSet
}

func (v *NullableV1beta1ImportValidationItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1beta1ImportValidationItem(val *V1beta1ImportValidationItem) *NullableV1beta1ImportValidationItem {
	return &NullableV1beta1ImportValidationItem{value: val, isSet: true}
}

func (v NullableV1beta1ImportValidationItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1beta1ImportValidationItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
