/*
TiDB Cloud Dedicated Import API

TiDB Cloud Dedicated Import API (subset of the TiDB Cloud Dedicated API, generated from tidbcloud-oas-v1beta1-dedicated.swagger.json)

API version: v1beta1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package imp

import (
	"encoding/json"
	"fmt"
)

// V1beta1ImportAzureBlobAuthTypeEnum The type of the access method.   - UNSPECIFIED: The access method is unknown.  - SAS_TOKEN: The access method is sas token.
type V1beta1ImportAzureBlobAuthTypeEnum string

// List of v1beta1ImportAzureBlobAuthTypeEnum
const (
	V1BETA1IMPORTAZUREBLOBAUTHTYPEENUM_UNSPECIFIED V1beta1ImportAzureBlobAuthTypeEnum = "UNSPECIFIED"
	V1BETA1IMPORTAZUREBLOBAUTHTYPEENUM_SAS_TOKEN   V1beta1ImportAzureBlobAuthTypeEnum = "SAS_TOKEN"
)

// All allowed values of V1beta1ImportAzureBlobAuthTypeEnum enum
var AllowedV1beta1ImportAzureBlobAuthTypeEnumEnumValues = []V1beta1ImportAzureBlobAuthTypeEnum{
	"UNSPECIFIED",
	"SAS_TOKEN",
}

func (v *V1beta1ImportAzureBlobAuthTypeEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := V1beta1ImportAzureBlobAuthTypeEnum(value)
	for _, existing := range AllowedV1beta1ImportAzureBlobAuthTypeEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid V1beta1ImportAzureBlobAuthTypeEnum", value)
}

// NewV1beta1ImportAzureBlobAuthTypeEnumFromValue returns a pointer to a valid V1beta1ImportAzureBlobAuthTypeEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewV1beta1ImportAzureBlobAuthTypeEnumFromValue(v string) (*V1beta1ImportAzureBlobAuthTypeEnum, error) {
	ev := V1beta1ImportAzureBlobAuthTypeEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for V1beta1ImportAzureBlobAuthTypeEnum: valid values are %v", v, AllowedV1beta1ImportAzureBlobAuthTypeEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v V1beta1ImportAzureBlobAuthTypeEnum) IsValid() bool {
	for _, existing := range AllowedV1beta1ImportAzureBlobAuthTypeEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to v1beta1ImportAzureBlobAuthTypeEnum value
func (v V1beta1ImportAzureBlobAuthTypeEnum) Ptr() *V1beta1ImportAzureBlobAuthTypeEnum {
	return &v
}

type NullableV1beta1ImportAzureBlobAuthTypeEnum struct {
	value *V1beta1ImportAzureBlobAuthTypeEnum
	isSet bool
}

func (v NullableV1beta1ImportAzureBlobAuthTypeEnum) Get() *V1beta1ImportAzureBlobAuthTypeEnum {
	return v.value
}

func (v *NullableV1beta1ImportAzureBlobAuthTypeEnum) Set(val *V1beta1ImportAzureBlobAuthTypeEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableV1beta1ImportAzureBlobAuthTypeEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableV1beta1ImportAzureBlobAuthTypeEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1beta1ImportAzureBlobAuthTypeEnum(val *V1beta1ImportAzureBlobAuthTypeEnum) *NullableV1beta1ImportAzureBlobAuthTypeEnum {
	return &NullableV1beta1ImportAzureBlobAuthTypeEnum{value: val, isSet: true}
}

func (v NullableV1beta1ImportAzureBlobAuthTypeEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1beta1ImportAzureBlobAuthTypeEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
