/*
TiDB Cloud Dedicated Import API

TiDB Cloud Dedicated Import API (subset of the TiDB Cloud Dedicated API, generated from tidbcloud-oas-v1beta1-dedicated.swagger.json)

API version: v1beta1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package imp

import (
	"encoding/json"
	"fmt"
)

// V1beta1ImportFileTypeEnum The type of the file.   - UNSPECIFIED: The type of the file is unknown.  - CSV: CSV type.  - SQL: SQL type.  - AURORA_SNAPSHOT: Aurora snapshot type.  - PARQUET: Parquet type.
type V1beta1ImportFileTypeEnum string

// List of v1beta1ImportFileTypeEnum
const (
	V1BETA1IMPORTFILETYPEENUM_UNSPECIFIED     V1beta1ImportFileTypeEnum = "UNSPECIFIED"
	V1BETA1IMPORTFILETYPEENUM_CSV             V1beta1ImportFileTypeEnum = "CSV"
	V1BETA1IMPORTFILETYPEENUM_SQL             V1beta1ImportFileTypeEnum = "SQL"
	V1BETA1IMPORTFILETYPEENUM_AURORA_SNAPSHOT V1beta1ImportFileTypeEnum = "AURORA_SNAPSHOT"
	V1BETA1IMPORTFILETYPEENUM_PARQUET         V1beta1ImportFileTypeEnum = "PARQUET"
)

// All allowed values of V1beta1ImportFileTypeEnum enum
var AllowedV1beta1ImportFileTypeEnumEnumValues = []V1beta1ImportFileTypeEnum{
	"UNSPECIFIED",
	"CSV",
	"SQL",
	"AURORA_SNAPSHOT",
	"PARQUET",
}

func (v *V1beta1ImportFileTypeEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := V1beta1ImportFileTypeEnum(value)
	for _, existing := range AllowedV1beta1ImportFileTypeEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid V1beta1ImportFileTypeEnum", value)
}

// NewV1beta1ImportFileTypeEnumFromValue returns a pointer to a valid V1beta1ImportFileTypeEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewV1beta1ImportFileTypeEnumFromValue(v string) (*V1beta1ImportFileTypeEnum, error) {
	ev := V1beta1ImportFileTypeEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for V1beta1ImportFileTypeEnum: valid values are %v", v, AllowedV1beta1ImportFileTypeEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v V1beta1ImportFileTypeEnum) IsValid() bool {
	for _, existing := range AllowedV1beta1ImportFileTypeEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to v1beta1ImportFileTypeEnum value
func (v V1beta1ImportFileTypeEnum) Ptr() *V1beta1ImportFileTypeEnum {
	return &v
}

type NullableV1beta1ImportFileTypeEnum struct {
	value *V1beta1ImportFileTypeEnum
	isSet bool
}

func (v NullableV1beta1ImportFileTypeEnum) Get() *V1beta1ImportFileTypeEnum {
	return v.value
}

func (v *NullableV1beta1ImportFileTypeEnum) Set(val *V1beta1ImportFileTypeEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableV1beta1ImportFileTypeEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableV1beta1ImportFileTypeEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1beta1ImportFileTypeEnum(val *V1beta1ImportFileTypeEnum) *NullableV1beta1ImportFileTypeEnum {
	return &NullableV1beta1ImportFileTypeEnum{value: val, isSet: true}
}

func (v NullableV1beta1ImportFileTypeEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1beta1ImportFileTypeEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
