/*
TiDB Cloud Dedicated Import API

TiDB Cloud Dedicated Import API (subset of the TiDB Cloud Dedicated API, generated from tidbcloud-oas-v1beta1-dedicated.swagger.json)

API version: v1beta1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package imp

import (
	"encoding/json"
	"fmt"
)

// checks if the V1beta1ImportSource type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1beta1ImportSource{}

// V1beta1ImportSource The source of the import.
type V1beta1ImportSource struct {
	// The source from which data is imported.  When this field is set, the corresponding configuration field must also be provided. For example, if type is `S3`, the `s3` field must be specified.  - `\"UNSPECIFIED\"`: the import source is not specified.  - `\"S3\"`: import from Amazon S3.  - `\"GCS\"`: import from Google Cloud Storage.  - `\"AZURE_BLOB\"`: import from Azure Blob Storage.
	Type V1beta1ImportSourceTypeEnum `json:"type"`
	// The configuration details for importing from Amazon S3. This is required when `type` is `S3`.
	S3 *V1beta1S3Source `json:"s3,omitempty"`
	// The configuration details for importing from Google Cloud Storage. This is required when `type` is `GCS`.
	Gcs *V1beta1GCSSource `json:"gcs,omitempty"`
	// The configuration details for importing from Azure Blob Storage. This is required when `type` is `AZURE_BLOB`.
	AzureBlob            *V1beta1AzureBlobSource `json:"azureBlob,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _V1beta1ImportSource V1beta1ImportSource

// NewV1beta1ImportSource instantiates a new V1beta1ImportSource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1beta1ImportSource(type_ V1beta1ImportSourceTypeEnum) *V1beta1ImportSource {
	this := V1beta1ImportSource{}
	this.Type = type_
	return &this
}

// NewV1beta1ImportSourceWithDefaults instantiates a new V1beta1ImportSource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1beta1ImportSourceWithDefaults() *V1beta1ImportSource {
	this := V1beta1ImportSource{}
	return &this
}

// GetType returns the Type field value
func (o *V1beta1ImportSource) GetType() V1beta1ImportSourceTypeEnum {
	if o == nil {
		var ret V1beta1ImportSourceTypeEnum
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *V1beta1ImportSource) GetTypeOk() (*V1beta1ImportSourceTypeEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *V1beta1ImportSource) SetType(v V1beta1ImportSourceTypeEnum) {
	o.Type = v
}

// GetS3 returns the S3 field value if set, zero value otherwise.
func (o *V1beta1ImportSource) GetS3() V1beta1S3Source {
	if o == nil || IsNil(o.S3) {
		var ret V1beta1S3Source
		return ret
	}
	return *o.S3
}

// GetS3Ok returns a tuple with the S3 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1beta1ImportSource) GetS3Ok() (*V1beta1S3Source, bool) {
	if o == nil || IsNil(o.S3) {
		return nil, false
	}
	return o.S3, true
}

// HasS3 returns a boolean if a field has been set.
func (o *V1beta1ImportSource) HasS3() bool {
	if o != nil && !IsNil(o.S3) {
		return true
	}

	return false
}

// SetS3 gets a reference to the given V1beta1S3Source and assigns it to the S3 field.
func (o *V1beta1ImportSource) SetS3(v V1beta1S3Source) {
	o.S3 = &v
}

// GetGcs returns the Gcs field value if set, zero value otherwise.
func (o *V1beta1ImportSource) GetGcs() V1beta1GCSSource {
	if o == nil || IsNil(o.Gcs) {
		var ret V1beta1GCSSource
		return ret
	}
	return *o.Gcs
}

// GetGcsOk returns a tuple with the Gcs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1beta1ImportSource) GetGcsOk() (*V1beta1GCSSource, bool) {
	if o == nil || IsNil(o.Gcs) {
		return nil, false
	}
	return o.Gcs, true
}

// HasGcs returns a boolean if a field has been set.
func (o *V1beta1ImportSource) HasGcs() bool {
	if o != nil && !IsNil(o.Gcs) {
		return true
	}

	return false
}

// SetGcs gets a reference to the given V1beta1GCSSource and assigns it to the Gcs field.
func (o *V1beta1ImportSource) SetGcs(v V1beta1GCSSource) {
	o.Gcs = &v
}

// GetAzureBlob returns the AzureBlob field value if set, zero value otherwise.
func (o *V1beta1ImportSource) GetAzureBlob() V1beta1AzureBlobSource {
	if o == nil || IsNil(o.AzureBlob) {
		var ret V1beta1AzureBlobSource
		return ret
	}
	return *o.AzureBlob
}

// GetAzureBlobOk returns a tuple with the AzureBlob field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1beta1ImportSource) GetAzureBlobOk() (*V1beta1AzureBlobSource, bool) {
	if o == nil || IsNil(o.AzureBlob) {
		return nil, false
	}
	return o.AzureBlob, true
}

// HasAzureBlob returns a boolean if a field has been set.
func (o *V1beta1ImportSource) HasAzureBlob() bool {
	if o != nil && !IsNil(o.AzureBlob) {
		return true
	}

	return false
}

// SetAzureBlob gets a reference to the given V1beta1AzureBlobSource and assigns it to the AzureBlob field.
func (o *V1beta1ImportSource) SetAzureBlob(v V1beta1AzureBlobSource) {
	o.AzureBlob = &v
}

func (o V1beta1ImportSource) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1beta1ImportSource) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	if !IsNil(o.S3) {
		toSerialize["s3"] = o.S3
	}
	if !IsNil(o.Gcs) {
		toSerialize["gcs"] = o.Gcs
	}
	if !IsNil(o.AzureBlob) {
		toSerialize["azureBlob"] = o.AzureBlob
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *V1beta1ImportSource) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV1beta1ImportSource := _V1beta1ImportSource{}

	err = json.Unmarshal(data, &varV1beta1ImportSource)

	if err != nil {
		return err
	}

	*o = V1beta1ImportSource(varV1beta1ImportSource)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "s3")
		delete(additionalProperties, "gcs")
		delete(additionalProperties, "azureBlob")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableV1beta1ImportSource struct {
	value *V1beta1ImportSource
	isSet bool
}

func (v NullableV1beta1ImportSource) Get() *V1beta1ImportSource {
	return v.value
}

func (v *NullableV1beta1ImportSource) Set(val *V1beta1ImportSource) {
	v.value = val
	v.isSet = true
}

func (v NullableV1beta1ImportSource) IsSet() bool {
	return v.isSet
}

func (v *NullableV1beta1ImportSource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1beta1ImportSource(val *V1beta1ImportSource) *NullableV1beta1ImportSource {
	return &NullableV1beta1ImportSource{value: val, isSet: true}
}

func (v NullableV1beta1ImportSource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1beta1ImportSource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
