/*
TiDB Cloud Dedicated Import API

TiDB Cloud Dedicated Import API (subset of the TiDB Cloud Dedicated API, generated from tidbcloud-oas-v1beta1-dedicated.swagger.json)

API version: v1beta1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package imp

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the V1beta1GCSSource type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1beta1GCSSource{}

// V1beta1GCSSource The Google Cloud Storage source of the import.
type V1beta1GCSSource struct {
	// The Google Cloud Storage URI of the import source.
	Uri string `json:"uri"`
	// The authentication method for accessing the Google Cloud Storage source.
	AuthType V1beta1ImportGcsAuthTypeEnum `json:"authType"`
	// The service account key for accessing the Google Cloud Storage source.
	ServiceAccountKey *string `json:"serviceAccountKey,omitempty"`
}

type _V1beta1GCSSource V1beta1GCSSource

// NewV1beta1GCSSource instantiates a new V1beta1GCSSource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1beta1GCSSource(uri string, authType V1beta1ImportGcsAuthTypeEnum) *V1beta1GCSSource {
	this := V1beta1GCSSource{}
	this.Uri = uri
	this.AuthType = authType
	return &this
}

// NewV1beta1GCSSourceWithDefaults instantiates a new V1beta1GCSSource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1beta1GCSSourceWithDefaults() *V1beta1GCSSource {
	this := V1beta1GCSSource{}
	return &this
}

// GetUri returns the Uri field value
func (o *V1beta1GCSSource) GetUri() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uri
}

// GetUriOk returns a tuple with the Uri field value
// and a boolean to check if the value has been set.
func (o *V1beta1GCSSource) GetUriOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uri, true
}

// SetUri sets field value
func (o *V1beta1GCSSource) SetUri(v string) {
	o.Uri = v
}

// GetAuthType returns the AuthType field value
func (o *V1beta1GCSSource) GetAuthType() V1beta1ImportGcsAuthTypeEnum {
	if o == nil {
		var ret V1beta1ImportGcsAuthTypeEnum
		return ret
	}

	return o.AuthType
}

// GetAuthTypeOk returns a tuple with the AuthType field value
// and a boolean to check if the value has been set.
func (o *V1beta1GCSSource) GetAuthTypeOk() (*V1beta1ImportGcsAuthTypeEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuthType, true
}

// SetAuthType sets field value
func (o *V1beta1GCSSource) SetAuthType(v V1beta1ImportGcsAuthTypeEnum) {
	o.AuthType = v
}

// GetServiceAccountKey returns the ServiceAccountKey field value if set, zero value otherwise.
func (o *V1beta1GCSSource) GetServiceAccountKey() string {
	if o == nil || IsNil(o.ServiceAccountKey) {
		var ret string
		return ret
	}
	return *o.ServiceAccountKey
}

// GetServiceAccountKeyOk returns a tuple with the ServiceAccountKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1beta1GCSSource) GetServiceAccountKeyOk() (*string, bool) {
	if o == nil || IsNil(o.ServiceAccountKey) {
		return nil, false
	}
	return o.ServiceAccountKey, true
}

// HasServiceAccountKey returns a boolean if a field has been set.
func (o *V1beta1GCSSource) HasServiceAccountKey() bool {
	if o != nil && !IsNil(o.ServiceAccountKey) {
		return true
	}

	return false
}

// SetServiceAccountKey gets a reference to the given string and assigns it to the ServiceAccountKey field.
func (o *V1beta1GCSSource) SetServiceAccountKey(v string) {
	o.ServiceAccountKey = &v
}

func (o V1beta1GCSSource) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1beta1GCSSource) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["uri"] = o.Uri
	toSerialize["authType"] = o.AuthType
	if !IsNil(o.ServiceAccountKey) {
		toSerialize["serviceAccountKey"] = o.ServiceAccountKey
	}
	return toSerialize, nil
}

func (o *V1beta1GCSSource) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"uri",
		"authType",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV1beta1GCSSource := _V1beta1GCSSource{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV1beta1GCSSource)

	if err != nil {
		return err
	}

	*o = V1beta1GCSSource(varV1beta1GCSSource)

	return err
}

type NullableV1beta1GCSSource struct {
	value *V1beta1GCSSource
	isSet bool
}

func (v NullableV1beta1GCSSource) Get() *V1beta1GCSSource {
	return v.value
}

func (v *NullableV1beta1GCSSource) Set(val *V1beta1GCSSource) {
	v.value = val
	v.isSet = true
}

func (v NullableV1beta1GCSSource) IsSet() bool {
	return v.isSet
}

func (v *NullableV1beta1GCSSource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1beta1GCSSource(val *V1beta1GCSSource) *NullableV1beta1GCSSource {
	return &NullableV1beta1GCSSource{value: val, isSet: true}
}

func (v NullableV1beta1GCSSource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1beta1GCSSource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
