/*
TiDB Cloud Dedicated Import API

TiDB Cloud Dedicated Import API (subset of the TiDB Cloud Dedicated API, generated from tidbcloud-oas-v1beta1-dedicated.swagger.json)

API version: v1beta1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package imp

import (
	"encoding/json"
	"fmt"
)

// V1beta1ImportSourceTypeEnum The source type of the import.   - UNSPECIFIED: Indicates that the import source is not specified.  - S3: Indicates that the import source is an AWS S3 resource.  - GCS: Indicates that the import source is a Google Cloud Storage resource.  - AZURE_BLOB: Indicates that the import source is an Azure Blob Storage resource.
type V1beta1ImportSourceTypeEnum string

// List of v1beta1ImportSourceTypeEnum
const (
	V1BETA1IMPORTSOURCETYPEENUM_UNSPECIFIED V1beta1ImportSourceTypeEnum = "UNSPECIFIED"
	V1BETA1IMPORTSOURCETYPEENUM_S3          V1beta1ImportSourceTypeEnum = "S3"
	V1BETA1IMPORTSOURCETYPEENUM_GCS         V1beta1ImportSourceTypeEnum = "GCS"
	V1BETA1IMPORTSOURCETYPEENUM_AZURE_BLOB  V1beta1ImportSourceTypeEnum = "AZURE_BLOB"
)

// All allowed values of V1beta1ImportSourceTypeEnum enum
var AllowedV1beta1ImportSourceTypeEnumEnumValues = []V1beta1ImportSourceTypeEnum{
	"UNSPECIFIED",
	"S3",
	"GCS",
	"AZURE_BLOB",
}

func (v *V1beta1ImportSourceTypeEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := V1beta1ImportSourceTypeEnum(value)
	for _, existing := range AllowedV1beta1ImportSourceTypeEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid V1beta1ImportSourceTypeEnum", value)
}

// NewV1beta1ImportSourceTypeEnumFromValue returns a pointer to a valid V1beta1ImportSourceTypeEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewV1beta1ImportSourceTypeEnumFromValue(v string) (*V1beta1ImportSourceTypeEnum, error) {
	ev := V1beta1ImportSourceTypeEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for V1beta1ImportSourceTypeEnum: valid values are %v", v, AllowedV1beta1ImportSourceTypeEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v V1beta1ImportSourceTypeEnum) IsValid() bool {
	for _, existing := range AllowedV1beta1ImportSourceTypeEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to v1beta1ImportSourceTypeEnum value
func (v V1beta1ImportSourceTypeEnum) Ptr() *V1beta1ImportSourceTypeEnum {
	return &v
}

type NullableV1beta1ImportSourceTypeEnum struct {
	value *V1beta1ImportSourceTypeEnum
	isSet bool
}

func (v NullableV1beta1ImportSourceTypeEnum) Get() *V1beta1ImportSourceTypeEnum {
	return v.value
}

func (v *NullableV1beta1ImportSourceTypeEnum) Set(val *V1beta1ImportSourceTypeEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableV1beta1ImportSourceTypeEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableV1beta1ImportSourceTypeEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1beta1ImportSourceTypeEnum(val *V1beta1ImportSourceTypeEnum) *NullableV1beta1ImportSourceTypeEnum {
	return &NullableV1beta1ImportSourceTypeEnum{value: val, isSet: true}
}

func (v NullableV1beta1ImportSourceTypeEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1beta1ImportSourceTypeEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
