/*
TiDB Cloud Dedicated Import API

TiDB Cloud Dedicated Import API (subset of the TiDB Cloud Dedicated API, generated from tidbcloud-oas-v1beta1-dedicated.swagger.json)

API version: v1beta1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package imp

import (
	"encoding/json"
	"fmt"
)

// checks if the V1beta1ImportOptions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1beta1ImportOptions{}

// V1beta1ImportOptions The options of the import task.
type V1beta1ImportOptions struct {
	// The format of the file to import.  - `\"CSV\"`: CSV files. For more information, see [Import CSV Files from Cloud Storage into TiDB Cloud Dedicated](https://docs.pingcap.com/tidbcloud/import-csv-files/).  - `\"PARQUET\"`: Apache Parquet files. For more information, see [Import Apache Parquet Files from Cloud Storage into TiDB Cloud Dedicated](https://docs.pingcap.com/tidbcloud/import-parquet-files/).  - `\"SQL\"`: SQL files.  - `\"AURORA_SNAPSHOT\"`: Amazon Aurora snapshot files.
	FileType V1beta1ImportFileTypeEnum `json:"fileType"`
	// The format specification for CSV files.
	CsvFormat *V1beta1CSVFormat `json:"csvFormat,omitempty"`
	// Specifies how to handle duplicate records when importing SQL files.  - `\"UNSPECIFIED\"`: the behavior is undefined.  - `\"REPLACE\"`: existing rows are replaced with new data from the import file.  - `\"IGNORE\"`: duplicate rows are skipped.  - `\"ERROR\"`: the import fails if a duplicate row is found.
	DuplicationHandling *V1beta1DuplicationHandlingForSQLEnum `json:"duplicationHandling,omitempty"`
	// If set to `true`, the request is validated but not executed. Defaults to `false`.
	ValidateOnly         *bool `json:"validateOnly,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _V1beta1ImportOptions V1beta1ImportOptions

// NewV1beta1ImportOptions instantiates a new V1beta1ImportOptions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1beta1ImportOptions(fileType V1beta1ImportFileTypeEnum) *V1beta1ImportOptions {
	this := V1beta1ImportOptions{}
	this.FileType = fileType
	return &this
}

// NewV1beta1ImportOptionsWithDefaults instantiates a new V1beta1ImportOptions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1beta1ImportOptionsWithDefaults() *V1beta1ImportOptions {
	this := V1beta1ImportOptions{}
	return &this
}

// GetFileType returns the FileType field value
func (o *V1beta1ImportOptions) GetFileType() V1beta1ImportFileTypeEnum {
	if o == nil {
		var ret V1beta1ImportFileTypeEnum
		return ret
	}

	return o.FileType
}

// GetFileTypeOk returns a tuple with the FileType field value
// and a boolean to check if the value has been set.
func (o *V1beta1ImportOptions) GetFileTypeOk() (*V1beta1ImportFileTypeEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FileType, true
}

// SetFileType sets field value
func (o *V1beta1ImportOptions) SetFileType(v V1beta1ImportFileTypeEnum) {
	o.FileType = v
}

// GetCsvFormat returns the CsvFormat field value if set, zero value otherwise.
func (o *V1beta1ImportOptions) GetCsvFormat() V1beta1CSVFormat {
	if o == nil || IsNil(o.CsvFormat) {
		var ret V1beta1CSVFormat
		return ret
	}
	return *o.CsvFormat
}

// GetCsvFormatOk returns a tuple with the CsvFormat field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1beta1ImportOptions) GetCsvFormatOk() (*V1beta1CSVFormat, bool) {
	if o == nil || IsNil(o.CsvFormat) {
		return nil, false
	}
	return o.CsvFormat, true
}

// HasCsvFormat returns a boolean if a field has been set.
func (o *V1beta1ImportOptions) HasCsvFormat() bool {
	if o != nil && !IsNil(o.CsvFormat) {
		return true
	}

	return false
}

// SetCsvFormat gets a reference to the given V1beta1CSVFormat and assigns it to the CsvFormat field.
func (o *V1beta1ImportOptions) SetCsvFormat(v V1beta1CSVFormat) {
	o.CsvFormat = &v
}

// GetDuplicationHandling returns the DuplicationHandling field value if set, zero value otherwise.
func (o *V1beta1ImportOptions) GetDuplicationHandling() V1beta1DuplicationHandlingForSQLEnum {
	if o == nil || IsNil(o.DuplicationHandling) {
		var ret V1beta1DuplicationHandlingForSQLEnum
		return ret
	}
	return *o.DuplicationHandling
}

// GetDuplicationHandlingOk returns a tuple with the DuplicationHandling field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1beta1ImportOptions) GetDuplicationHandlingOk() (*V1beta1DuplicationHandlingForSQLEnum, bool) {
	if o == nil || IsNil(o.DuplicationHandling) {
		return nil, false
	}
	return o.DuplicationHandling, true
}

// HasDuplicationHandling returns a boolean if a field has been set.
func (o *V1beta1ImportOptions) HasDuplicationHandling() bool {
	if o != nil && !IsNil(o.DuplicationHandling) {
		return true
	}

	return false
}

// SetDuplicationHandling gets a reference to the given V1beta1DuplicationHandlingForSQLEnum and assigns it to the DuplicationHandling field.
func (o *V1beta1ImportOptions) SetDuplicationHandling(v V1beta1DuplicationHandlingForSQLEnum) {
	o.DuplicationHandling = &v
}

// GetValidateOnly returns the ValidateOnly field value if set, zero value otherwise.
func (o *V1beta1ImportOptions) GetValidateOnly() bool {
	if o == nil || IsNil(o.ValidateOnly) {
		var ret bool
		return ret
	}
	return *o.ValidateOnly
}

// GetValidateOnlyOk returns a tuple with the ValidateOnly field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1beta1ImportOptions) GetValidateOnlyOk() (*bool, bool) {
	if o == nil || IsNil(o.ValidateOnly) {
		return nil, false
	}
	return o.ValidateOnly, true
}

// HasValidateOnly returns a boolean if a field has been set.
func (o *V1beta1ImportOptions) HasValidateOnly() bool {
	if o != nil && !IsNil(o.ValidateOnly) {
		return true
	}

	return false
}

// SetValidateOnly gets a reference to the given bool and assigns it to the ValidateOnly field.
func (o *V1beta1ImportOptions) SetValidateOnly(v bool) {
	o.ValidateOnly = &v
}

func (o V1beta1ImportOptions) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1beta1ImportOptions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["fileType"] = o.FileType
	if !IsNil(o.CsvFormat) {
		toSerialize["csvFormat"] = o.CsvFormat
	}
	if !IsNil(o.DuplicationHandling) {
		toSerialize["duplicationHandling"] = o.DuplicationHandling
	}
	if !IsNil(o.ValidateOnly) {
		toSerialize["validateOnly"] = o.ValidateOnly
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *V1beta1ImportOptions) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"fileType",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV1beta1ImportOptions := _V1beta1ImportOptions{}

	err = json.Unmarshal(data, &varV1beta1ImportOptions)

	if err != nil {
		return err
	}

	*o = V1beta1ImportOptions(varV1beta1ImportOptions)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "fileType")
		delete(additionalProperties, "csvFormat")
		delete(additionalProperties, "duplicationHandling")
		delete(additionalProperties, "validateOnly")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableV1beta1ImportOptions struct {
	value *V1beta1ImportOptions
	isSet bool
}

func (v NullableV1beta1ImportOptions) Get() *V1beta1ImportOptions {
	return v.value
}

func (v *NullableV1beta1ImportOptions) Set(val *V1beta1ImportOptions) {
	v.value = val
	v.isSet = true
}

func (v NullableV1beta1ImportOptions) IsSet() bool {
	return v.isSet
}

func (v *NullableV1beta1ImportOptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1beta1ImportOptions(val *V1beta1ImportOptions) *NullableV1beta1ImportOptions {
	return &NullableV1beta1ImportOptions{value: val, isSet: true}
}

func (v NullableV1beta1ImportOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1beta1ImportOptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
