/*
TiDB Cloud Dedicated Import API

TiDB Cloud Dedicated Import API (subset of the TiDB Cloud Dedicated API, generated from tidbcloud-oas-v1beta1-dedicated.swagger.json)

API version: v1beta1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package imp

import (
	"encoding/json"
	"fmt"
)

// V1beta1ImportGcsAuthTypeEnum The type of the access method.   - UNSPECIFIED: The access method is unknown.  - SERVICE_ACCOUNT_KEY: The access method is service account key.
type V1beta1ImportGcsAuthTypeEnum string

// List of v1beta1ImportGcsAuthTypeEnum
const (
	V1BETA1IMPORTGCSAUTHTYPEENUM_UNSPECIFIED         V1beta1ImportGcsAuthTypeEnum = "UNSPECIFIED"
	V1BETA1IMPORTGCSAUTHTYPEENUM_SERVICE_ACCOUNT_KEY V1beta1ImportGcsAuthTypeEnum = "SERVICE_ACCOUNT_KEY"
)

// All allowed values of V1beta1ImportGcsAuthTypeEnum enum
var AllowedV1beta1ImportGcsAuthTypeEnumEnumValues = []V1beta1ImportGcsAuthTypeEnum{
	"UNSPECIFIED",
	"SERVICE_ACCOUNT_KEY",
}

func (v *V1beta1ImportGcsAuthTypeEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := V1beta1ImportGcsAuthTypeEnum(value)
	for _, existing := range AllowedV1beta1ImportGcsAuthTypeEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid V1beta1ImportGcsAuthTypeEnum", value)
}

// NewV1beta1ImportGcsAuthTypeEnumFromValue returns a pointer to a valid V1beta1ImportGcsAuthTypeEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewV1beta1ImportGcsAuthTypeEnumFromValue(v string) (*V1beta1ImportGcsAuthTypeEnum, error) {
	ev := V1beta1ImportGcsAuthTypeEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for V1beta1ImportGcsAuthTypeEnum: valid values are %v", v, AllowedV1beta1ImportGcsAuthTypeEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v V1beta1ImportGcsAuthTypeEnum) IsValid() bool {
	for _, existing := range AllowedV1beta1ImportGcsAuthTypeEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to v1beta1ImportGcsAuthTypeEnum value
func (v V1beta1ImportGcsAuthTypeEnum) Ptr() *V1beta1ImportGcsAuthTypeEnum {
	return &v
}

type NullableV1beta1ImportGcsAuthTypeEnum struct {
	value *V1beta1ImportGcsAuthTypeEnum
	isSet bool
}

func (v NullableV1beta1ImportGcsAuthTypeEnum) Get() *V1beta1ImportGcsAuthTypeEnum {
	return v.value
}

func (v *NullableV1beta1ImportGcsAuthTypeEnum) Set(val *V1beta1ImportGcsAuthTypeEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableV1beta1ImportGcsAuthTypeEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableV1beta1ImportGcsAuthTypeEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1beta1ImportGcsAuthTypeEnum(val *V1beta1ImportGcsAuthTypeEnum) *NullableV1beta1ImportGcsAuthTypeEnum {
	return &NullableV1beta1ImportGcsAuthTypeEnum{value: val, isSet: true}
}

func (v NullableV1beta1ImportGcsAuthTypeEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1beta1ImportGcsAuthTypeEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
