/*
TiDB Cloud Dedicated Import API

TiDB Cloud Dedicated Import API (subset of the TiDB Cloud Dedicated API, generated from tidbcloud-oas-v1beta1-dedicated.swagger.json)

API version: v1beta1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package imp

import (
	"encoding/json"
	"fmt"
)

// V1beta1ImportS3AuthTypeEnum The type of the access method.   - UNSPECIFIED: The access method is unknown.  - ROLE_ARN: The access method is role arn.  - ACCESS_KEY: The access method is access key.
type V1beta1ImportS3AuthTypeEnum string

// List of v1beta1ImportS3AuthTypeEnum
const (
	V1BETA1IMPORTS3AUTHTYPEENUM_UNSPECIFIED V1beta1ImportS3AuthTypeEnum = "UNSPECIFIED"
	V1BETA1IMPORTS3AUTHTYPEENUM_ROLE_ARN    V1beta1ImportS3AuthTypeEnum = "ROLE_ARN"
	V1BETA1IMPORTS3AUTHTYPEENUM_ACCESS_KEY  V1beta1ImportS3AuthTypeEnum = "ACCESS_KEY"
)

// All allowed values of V1beta1ImportS3AuthTypeEnum enum
var AllowedV1beta1ImportS3AuthTypeEnumEnumValues = []V1beta1ImportS3AuthTypeEnum{
	"UNSPECIFIED",
	"ROLE_ARN",
	"ACCESS_KEY",
}

func (v *V1beta1ImportS3AuthTypeEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := V1beta1ImportS3AuthTypeEnum(value)
	for _, existing := range AllowedV1beta1ImportS3AuthTypeEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid V1beta1ImportS3AuthTypeEnum", value)
}

// NewV1beta1ImportS3AuthTypeEnumFromValue returns a pointer to a valid V1beta1ImportS3AuthTypeEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewV1beta1ImportS3AuthTypeEnumFromValue(v string) (*V1beta1ImportS3AuthTypeEnum, error) {
	ev := V1beta1ImportS3AuthTypeEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for V1beta1ImportS3AuthTypeEnum: valid values are %v", v, AllowedV1beta1ImportS3AuthTypeEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v V1beta1ImportS3AuthTypeEnum) IsValid() bool {
	for _, existing := range AllowedV1beta1ImportS3AuthTypeEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to v1beta1ImportS3AuthTypeEnum value
func (v V1beta1ImportS3AuthTypeEnum) Ptr() *V1beta1ImportS3AuthTypeEnum {
	return &v
}

type NullableV1beta1ImportS3AuthTypeEnum struct {
	value *V1beta1ImportS3AuthTypeEnum
	isSet bool
}

func (v NullableV1beta1ImportS3AuthTypeEnum) Get() *V1beta1ImportS3AuthTypeEnum {
	return v.value
}

func (v *NullableV1beta1ImportS3AuthTypeEnum) Set(val *V1beta1ImportS3AuthTypeEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableV1beta1ImportS3AuthTypeEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableV1beta1ImportS3AuthTypeEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1beta1ImportS3AuthTypeEnum(val *V1beta1ImportS3AuthTypeEnum) *NullableV1beta1ImportS3AuthTypeEnum {
	return &NullableV1beta1ImportS3AuthTypeEnum{value: val, isSet: true}
}

func (v NullableV1beta1ImportS3AuthTypeEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1beta1ImportS3AuthTypeEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
