/*
TiDB Cloud Dedicated Import API

TiDB Cloud Dedicated Import API (subset of the TiDB Cloud Dedicated API, generated from tidbcloud-oas-v1beta1-dedicated.swagger.json)

API version: v1beta1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package imp

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the V1beta1AzureBlobSource type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1beta1AzureBlobSource{}

// V1beta1AzureBlobSource The Azure Blob Storage source of the import.
type V1beta1AzureBlobSource struct {
	// The authentication method for accessing the Azure Blob Storage source.
	AuthType V1beta1ImportAzureBlobAuthTypeEnum `json:"authType"`
	// The Shared Access Signature (SAS) token for accessing the Azure Blob Storage source. This field is input-only and not returned in responses.
	SasToken *string `json:"sasToken,omitempty"`
	// The Azure Blob Storage URI of the import source, in the format of `azure://<account>.blob.core.windows.net/<container>/<path>` or `https://<account>.blob.core.windows.net/<container>/<path>`.
	Uri string `json:"uri"`
}

type _V1beta1AzureBlobSource V1beta1AzureBlobSource

// NewV1beta1AzureBlobSource instantiates a new V1beta1AzureBlobSource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1beta1AzureBlobSource(authType V1beta1ImportAzureBlobAuthTypeEnum, uri string) *V1beta1AzureBlobSource {
	this := V1beta1AzureBlobSource{}
	this.AuthType = authType
	this.Uri = uri
	return &this
}

// NewV1beta1AzureBlobSourceWithDefaults instantiates a new V1beta1AzureBlobSource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1beta1AzureBlobSourceWithDefaults() *V1beta1AzureBlobSource {
	this := V1beta1AzureBlobSource{}
	return &this
}

// GetAuthType returns the AuthType field value
func (o *V1beta1AzureBlobSource) GetAuthType() V1beta1ImportAzureBlobAuthTypeEnum {
	if o == nil {
		var ret V1beta1ImportAzureBlobAuthTypeEnum
		return ret
	}

	return o.AuthType
}

// GetAuthTypeOk returns a tuple with the AuthType field value
// and a boolean to check if the value has been set.
func (o *V1beta1AzureBlobSource) GetAuthTypeOk() (*V1beta1ImportAzureBlobAuthTypeEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuthType, true
}

// SetAuthType sets field value
func (o *V1beta1AzureBlobSource) SetAuthType(v V1beta1ImportAzureBlobAuthTypeEnum) {
	o.AuthType = v
}

// GetSasToken returns the SasToken field value if set, zero value otherwise.
func (o *V1beta1AzureBlobSource) GetSasToken() string {
	if o == nil || IsNil(o.SasToken) {
		var ret string
		return ret
	}
	return *o.SasToken
}

// GetSasTokenOk returns a tuple with the SasToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1beta1AzureBlobSource) GetSasTokenOk() (*string, bool) {
	if o == nil || IsNil(o.SasToken) {
		return nil, false
	}
	return o.SasToken, true
}

// HasSasToken returns a boolean if a field has been set.
func (o *V1beta1AzureBlobSource) HasSasToken() bool {
	if o != nil && !IsNil(o.SasToken) {
		return true
	}

	return false
}

// SetSasToken gets a reference to the given string and assigns it to the SasToken field.
func (o *V1beta1AzureBlobSource) SetSasToken(v string) {
	o.SasToken = &v
}

// GetUri returns the Uri field value
func (o *V1beta1AzureBlobSource) GetUri() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uri
}

// GetUriOk returns a tuple with the Uri field value
// and a boolean to check if the value has been set.
func (o *V1beta1AzureBlobSource) GetUriOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uri, true
}

// SetUri sets field value
func (o *V1beta1AzureBlobSource) SetUri(v string) {
	o.Uri = v
}

func (o V1beta1AzureBlobSource) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1beta1AzureBlobSource) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["authType"] = o.AuthType
	if !IsNil(o.SasToken) {
		toSerialize["sasToken"] = o.SasToken
	}
	toSerialize["uri"] = o.Uri
	return toSerialize, nil
}

func (o *V1beta1AzureBlobSource) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"authType",
		"uri",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV1beta1AzureBlobSource := _V1beta1AzureBlobSource{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV1beta1AzureBlobSource)

	if err != nil {
		return err
	}

	*o = V1beta1AzureBlobSource(varV1beta1AzureBlobSource)

	return err
}

type NullableV1beta1AzureBlobSource struct {
	value *V1beta1AzureBlobSource
	isSet bool
}

func (v NullableV1beta1AzureBlobSource) Get() *V1beta1AzureBlobSource {
	return v.value
}

func (v *NullableV1beta1AzureBlobSource) Set(val *V1beta1AzureBlobSource) {
	v.value = val
	v.isSet = true
}

func (v NullableV1beta1AzureBlobSource) IsSet() bool {
	return v.isSet
}

func (v *NullableV1beta1AzureBlobSource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1beta1AzureBlobSource(val *V1beta1AzureBlobSource) *NullableV1beta1AzureBlobSource {
	return &NullableV1beta1AzureBlobSource{value: val, isSet: true}
}

func (v NullableV1beta1AzureBlobSource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1beta1AzureBlobSource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
