/*
TiDB Cloud Dedicated Import API

TiDB Cloud Dedicated Import API (subset of the TiDB Cloud Dedicated API, generated from tidbcloud-oas-v1beta1-dedicated.swagger.json)

API version: v1beta1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package imp

import (
	"encoding/json"
	"fmt"
)

// V1beta1DuplicationHandlingForSQLEnum The duplication handling for SQL.   - UNSPECIFIED: The duplication handling for SQL is unknown.  - REPLACE: The duplication handling for SQL is replace.  - IGNORE: The duplication handling for SQL is ignore.  - ERROR: The duplication handling for SQL is error.
type V1beta1DuplicationHandlingForSQLEnum string

// List of v1beta1DuplicationHandlingForSQLEnum
const (
	V1BETA1DUPLICATIONHANDLINGFORSQLENUM_UNSPECIFIED V1beta1DuplicationHandlingForSQLEnum = "UNSPECIFIED"
	V1BETA1DUPLICATIONHANDLINGFORSQLENUM_REPLACE     V1beta1DuplicationHandlingForSQLEnum = "REPLACE"
	V1BETA1DUPLICATIONHANDLINGFORSQLENUM_IGNORE      V1beta1DuplicationHandlingForSQLEnum = "IGNORE"
	V1BETA1DUPLICATIONHANDLINGFORSQLENUM_ERROR       V1beta1DuplicationHandlingForSQLEnum = "ERROR"
)

// All allowed values of V1beta1DuplicationHandlingForSQLEnum enum
var AllowedV1beta1DuplicationHandlingForSQLEnumEnumValues = []V1beta1DuplicationHandlingForSQLEnum{
	"UNSPECIFIED",
	"REPLACE",
	"IGNORE",
	"ERROR",
}

func (v *V1beta1DuplicationHandlingForSQLEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := V1beta1DuplicationHandlingForSQLEnum(value)
	for _, existing := range AllowedV1beta1DuplicationHandlingForSQLEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid V1beta1DuplicationHandlingForSQLEnum", value)
}

// NewV1beta1DuplicationHandlingForSQLEnumFromValue returns a pointer to a valid V1beta1DuplicationHandlingForSQLEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewV1beta1DuplicationHandlingForSQLEnumFromValue(v string) (*V1beta1DuplicationHandlingForSQLEnum, error) {
	ev := V1beta1DuplicationHandlingForSQLEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for V1beta1DuplicationHandlingForSQLEnum: valid values are %v", v, AllowedV1beta1DuplicationHandlingForSQLEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v V1beta1DuplicationHandlingForSQLEnum) IsValid() bool {
	for _, existing := range AllowedV1beta1DuplicationHandlingForSQLEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to v1beta1DuplicationHandlingForSQLEnum value
func (v V1beta1DuplicationHandlingForSQLEnum) Ptr() *V1beta1DuplicationHandlingForSQLEnum {
	return &v
}

type NullableV1beta1DuplicationHandlingForSQLEnum struct {
	value *V1beta1DuplicationHandlingForSQLEnum
	isSet bool
}

func (v NullableV1beta1DuplicationHandlingForSQLEnum) Get() *V1beta1DuplicationHandlingForSQLEnum {
	return v.value
}

func (v *NullableV1beta1DuplicationHandlingForSQLEnum) Set(val *V1beta1DuplicationHandlingForSQLEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableV1beta1DuplicationHandlingForSQLEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableV1beta1DuplicationHandlingForSQLEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1beta1DuplicationHandlingForSQLEnum(val *V1beta1DuplicationHandlingForSQLEnum) *NullableV1beta1DuplicationHandlingForSQLEnum {
	return &NullableV1beta1DuplicationHandlingForSQLEnum{value: val, isSet: true}
}

func (v NullableV1beta1DuplicationHandlingForSQLEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1beta1DuplicationHandlingForSQLEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
