/*
TiDB Cloud Dedicated Import API

TiDB Cloud Dedicated Import API (subset of the TiDB Cloud Dedicated API, generated from tidbcloud-oas-v1beta1-dedicated.swagger.json)

API version: v1beta1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package imp

import (
	"encoding/json"
)

// checks if the V1beta1CSVFormat type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1beta1CSVFormat{}

// V1beta1CSVFormat The format of the CSV file.
type V1beta1CSVFormat struct {
	// The character used to separate values in the CSV file.
	Separator *string `json:"separator,omitempty"`
	// The character used to enclose string values in the CSV file.
	Delimiter *string `json:"delimiter,omitempty"`
	// Indicates whether the first row of the CSV file contains column headers.
	Header *bool `json:"header,omitempty"`
	// Indicates whether the columns in the CSV file can be NULL.
	NotNull *bool `json:"notNull,omitempty"`
	// The string representation of NULL values in the CSV file.
	NullValue *string `json:"nullValue,omitempty"`
	// Indicates whether to escape backslashes in the CSV file.
	BackslashEscape *bool `json:"backslashEscape,omitempty"`
	// Indicates whether to remove trailing separators from each row in the CSV file.
	TrimLastSeparator    *bool `json:"trimLastSeparator,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _V1beta1CSVFormat V1beta1CSVFormat

// NewV1beta1CSVFormat instantiates a new V1beta1CSVFormat object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1beta1CSVFormat() *V1beta1CSVFormat {
	this := V1beta1CSVFormat{}
	var separator string = ","
	this.Separator = &separator
	var delimiter string = "\""
	this.Delimiter = &delimiter
	var header bool = true
	this.Header = &header
	var notNull bool = false
	this.NotNull = &notNull
	var nullValue string = "\\N"
	this.NullValue = &nullValue
	var backslashEscape bool = true
	this.BackslashEscape = &backslashEscape
	var trimLastSeparator bool = false
	this.TrimLastSeparator = &trimLastSeparator
	return &this
}

// NewV1beta1CSVFormatWithDefaults instantiates a new V1beta1CSVFormat object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1beta1CSVFormatWithDefaults() *V1beta1CSVFormat {
	this := V1beta1CSVFormat{}
	var separator string = ","
	this.Separator = &separator
	var delimiter string = "\""
	this.Delimiter = &delimiter
	var header bool = true
	this.Header = &header
	var notNull bool = false
	this.NotNull = &notNull
	var nullValue string = "\\N"
	this.NullValue = &nullValue
	var backslashEscape bool = true
	this.BackslashEscape = &backslashEscape
	var trimLastSeparator bool = false
	this.TrimLastSeparator = &trimLastSeparator
	return &this
}

// GetSeparator returns the Separator field value if set, zero value otherwise.
func (o *V1beta1CSVFormat) GetSeparator() string {
	if o == nil || IsNil(o.Separator) {
		var ret string
		return ret
	}
	return *o.Separator
}

// GetSeparatorOk returns a tuple with the Separator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1beta1CSVFormat) GetSeparatorOk() (*string, bool) {
	if o == nil || IsNil(o.Separator) {
		return nil, false
	}
	return o.Separator, true
}

// HasSeparator returns a boolean if a field has been set.
func (o *V1beta1CSVFormat) HasSeparator() bool {
	if o != nil && !IsNil(o.Separator) {
		return true
	}

	return false
}

// SetSeparator gets a reference to the given string and assigns it to the Separator field.
func (o *V1beta1CSVFormat) SetSeparator(v string) {
	o.Separator = &v
}

// GetDelimiter returns the Delimiter field value if set, zero value otherwise.
func (o *V1beta1CSVFormat) GetDelimiter() string {
	if o == nil || IsNil(o.Delimiter) {
		var ret string
		return ret
	}
	return *o.Delimiter
}

// GetDelimiterOk returns a tuple with the Delimiter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1beta1CSVFormat) GetDelimiterOk() (*string, bool) {
	if o == nil || IsNil(o.Delimiter) {
		return nil, false
	}
	return o.Delimiter, true
}

// HasDelimiter returns a boolean if a field has been set.
func (o *V1beta1CSVFormat) HasDelimiter() bool {
	if o != nil && !IsNil(o.Delimiter) {
		return true
	}

	return false
}

// SetDelimiter gets a reference to the given string and assigns it to the Delimiter field.
func (o *V1beta1CSVFormat) SetDelimiter(v string) {
	o.Delimiter = &v
}

// GetHeader returns the Header field value if set, zero value otherwise.
func (o *V1beta1CSVFormat) GetHeader() bool {
	if o == nil || IsNil(o.Header) {
		var ret bool
		return ret
	}
	return *o.Header
}

// GetHeaderOk returns a tuple with the Header field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1beta1CSVFormat) GetHeaderOk() (*bool, bool) {
	if o == nil || IsNil(o.Header) {
		return nil, false
	}
	return o.Header, true
}

// HasHeader returns a boolean if a field has been set.
func (o *V1beta1CSVFormat) HasHeader() bool {
	if o != nil && !IsNil(o.Header) {
		return true
	}

	return false
}

// SetHeader gets a reference to the given bool and assigns it to the Header field.
func (o *V1beta1CSVFormat) SetHeader(v bool) {
	o.Header = &v
}

// GetNotNull returns the NotNull field value if set, zero value otherwise.
func (o *V1beta1CSVFormat) GetNotNull() bool {
	if o == nil || IsNil(o.NotNull) {
		var ret bool
		return ret
	}
	return *o.NotNull
}

// GetNotNullOk returns a tuple with the NotNull field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1beta1CSVFormat) GetNotNullOk() (*bool, bool) {
	if o == nil || IsNil(o.NotNull) {
		return nil, false
	}
	return o.NotNull, true
}

// HasNotNull returns a boolean if a field has been set.
func (o *V1beta1CSVFormat) HasNotNull() bool {
	if o != nil && !IsNil(o.NotNull) {
		return true
	}

	return false
}

// SetNotNull gets a reference to the given bool and assigns it to the NotNull field.
func (o *V1beta1CSVFormat) SetNotNull(v bool) {
	o.NotNull = &v
}

// GetNullValue returns the NullValue field value if set, zero value otherwise.
func (o *V1beta1CSVFormat) GetNullValue() string {
	if o == nil || IsNil(o.NullValue) {
		var ret string
		return ret
	}
	return *o.NullValue
}

// GetNullValueOk returns a tuple with the NullValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1beta1CSVFormat) GetNullValueOk() (*string, bool) {
	if o == nil || IsNil(o.NullValue) {
		return nil, false
	}
	return o.NullValue, true
}

// HasNullValue returns a boolean if a field has been set.
func (o *V1beta1CSVFormat) HasNullValue() bool {
	if o != nil && !IsNil(o.NullValue) {
		return true
	}

	return false
}

// SetNullValue gets a reference to the given string and assigns it to the NullValue field.
func (o *V1beta1CSVFormat) SetNullValue(v string) {
	o.NullValue = &v
}

// GetBackslashEscape returns the BackslashEscape field value if set, zero value otherwise.
func (o *V1beta1CSVFormat) GetBackslashEscape() bool {
	if o == nil || IsNil(o.BackslashEscape) {
		var ret bool
		return ret
	}
	return *o.BackslashEscape
}

// GetBackslashEscapeOk returns a tuple with the BackslashEscape field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1beta1CSVFormat) GetBackslashEscapeOk() (*bool, bool) {
	if o == nil || IsNil(o.BackslashEscape) {
		return nil, false
	}
	return o.BackslashEscape, true
}

// HasBackslashEscape returns a boolean if a field has been set.
func (o *V1beta1CSVFormat) HasBackslashEscape() bool {
	if o != nil && !IsNil(o.BackslashEscape) {
		return true
	}

	return false
}

// SetBackslashEscape gets a reference to the given bool and assigns it to the BackslashEscape field.
func (o *V1beta1CSVFormat) SetBackslashEscape(v bool) {
	o.BackslashEscape = &v
}

// GetTrimLastSeparator returns the TrimLastSeparator field value if set, zero value otherwise.
func (o *V1beta1CSVFormat) GetTrimLastSeparator() bool {
	if o == nil || IsNil(o.TrimLastSeparator) {
		var ret bool
		return ret
	}
	return *o.TrimLastSeparator
}

// GetTrimLastSeparatorOk returns a tuple with the TrimLastSeparator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1beta1CSVFormat) GetTrimLastSeparatorOk() (*bool, bool) {
	if o == nil || IsNil(o.TrimLastSeparator) {
		return nil, false
	}
	return o.TrimLastSeparator, true
}

// HasTrimLastSeparator returns a boolean if a field has been set.
func (o *V1beta1CSVFormat) HasTrimLastSeparator() bool {
	if o != nil && !IsNil(o.TrimLastSeparator) {
		return true
	}

	return false
}

// SetTrimLastSeparator gets a reference to the given bool and assigns it to the TrimLastSeparator field.
func (o *V1beta1CSVFormat) SetTrimLastSeparator(v bool) {
	o.TrimLastSeparator = &v
}

func (o V1beta1CSVFormat) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1beta1CSVFormat) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Separator) {
		toSerialize["separator"] = o.Separator
	}
	if !IsNil(o.Delimiter) {
		toSerialize["delimiter"] = o.Delimiter
	}
	if !IsNil(o.Header) {
		toSerialize["header"] = o.Header
	}
	if !IsNil(o.NotNull) {
		toSerialize["notNull"] = o.NotNull
	}
	if !IsNil(o.NullValue) {
		toSerialize["nullValue"] = o.NullValue
	}
	if !IsNil(o.BackslashEscape) {
		toSerialize["backslashEscape"] = o.BackslashEscape
	}
	if !IsNil(o.TrimLastSeparator) {
		toSerialize["trimLastSeparator"] = o.TrimLastSeparator
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *V1beta1CSVFormat) UnmarshalJSON(data []byte) (err error) {
	varV1beta1CSVFormat := _V1beta1CSVFormat{}

	err = json.Unmarshal(data, &varV1beta1CSVFormat)

	if err != nil {
		return err
	}

	*o = V1beta1CSVFormat(varV1beta1CSVFormat)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "separator")
		delete(additionalProperties, "delimiter")
		delete(additionalProperties, "header")
		delete(additionalProperties, "notNull")
		delete(additionalProperties, "nullValue")
		delete(additionalProperties, "backslashEscape")
		delete(additionalProperties, "trimLastSeparator")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableV1beta1CSVFormat struct {
	value *V1beta1CSVFormat
	isSet bool
}

func (v NullableV1beta1CSVFormat) Get() *V1beta1CSVFormat {
	return v.value
}

func (v *NullableV1beta1CSVFormat) Set(val *V1beta1CSVFormat) {
	v.value = val
	v.isSet = true
}

func (v NullableV1beta1CSVFormat) IsSet() bool {
	return v.isSet
}

func (v *NullableV1beta1CSVFormat) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1beta1CSVFormat(val *V1beta1CSVFormat) *NullableV1beta1CSVFormat {
	return &NullableV1beta1CSVFormat{value: val, isSet: true}
}

func (v NullableV1beta1CSVFormat) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1beta1CSVFormat) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
