/*
TiDB Cloud Dedicated Import API

TiDB Cloud Dedicated Import API (subset of the TiDB Cloud Dedicated API, generated from tidbcloud-oas-v1beta1-dedicated.swagger.json)

API version: v1beta1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package imp

import (
	"encoding/json"
)

// checks if the V1beta1ImportTargetTableInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1beta1ImportTargetTableInfo{}

// V1beta1ImportTargetTableInfo The target table info of the import task.
type V1beta1ImportTargetTableInfo struct {
	// The target table where the data is imported.
	TargetTable *CommonTable `json:"targetTable,omitempty"`
	// The custom file URI to import data into the target table. If not specified, TiDB Cloud Dedicated uses the default naming conventions to match files to tables.
	CustomFile *string `json:"customFile,omitempty"`
	// The actual source file URI that is matched to this table during import processing.
	MatchedUri           *string `json:"matchedUri,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _V1beta1ImportTargetTableInfo V1beta1ImportTargetTableInfo

// NewV1beta1ImportTargetTableInfo instantiates a new V1beta1ImportTargetTableInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1beta1ImportTargetTableInfo() *V1beta1ImportTargetTableInfo {
	this := V1beta1ImportTargetTableInfo{}
	return &this
}

// NewV1beta1ImportTargetTableInfoWithDefaults instantiates a new V1beta1ImportTargetTableInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1beta1ImportTargetTableInfoWithDefaults() *V1beta1ImportTargetTableInfo {
	this := V1beta1ImportTargetTableInfo{}
	return &this
}

// GetTargetTable returns the TargetTable field value if set, zero value otherwise.
func (o *V1beta1ImportTargetTableInfo) GetTargetTable() CommonTable {
	if o == nil || IsNil(o.TargetTable) {
		var ret CommonTable
		return ret
	}
	return *o.TargetTable
}

// GetTargetTableOk returns a tuple with the TargetTable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1beta1ImportTargetTableInfo) GetTargetTableOk() (*CommonTable, bool) {
	if o == nil || IsNil(o.TargetTable) {
		return nil, false
	}
	return o.TargetTable, true
}

// HasTargetTable returns a boolean if a field has been set.
func (o *V1beta1ImportTargetTableInfo) HasTargetTable() bool {
	if o != nil && !IsNil(o.TargetTable) {
		return true
	}

	return false
}

// SetTargetTable gets a reference to the given CommonTable and assigns it to the TargetTable field.
func (o *V1beta1ImportTargetTableInfo) SetTargetTable(v CommonTable) {
	o.TargetTable = &v
}

// GetCustomFile returns the CustomFile field value if set, zero value otherwise.
func (o *V1beta1ImportTargetTableInfo) GetCustomFile() string {
	if o == nil || IsNil(o.CustomFile) {
		var ret string
		return ret
	}
	return *o.CustomFile
}

// GetCustomFileOk returns a tuple with the CustomFile field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1beta1ImportTargetTableInfo) GetCustomFileOk() (*string, bool) {
	if o == nil || IsNil(o.CustomFile) {
		return nil, false
	}
	return o.CustomFile, true
}

// HasCustomFile returns a boolean if a field has been set.
func (o *V1beta1ImportTargetTableInfo) HasCustomFile() bool {
	if o != nil && !IsNil(o.CustomFile) {
		return true
	}

	return false
}

// SetCustomFile gets a reference to the given string and assigns it to the CustomFile field.
func (o *V1beta1ImportTargetTableInfo) SetCustomFile(v string) {
	o.CustomFile = &v
}

// GetMatchedUri returns the MatchedUri field value if set, zero value otherwise.
func (o *V1beta1ImportTargetTableInfo) GetMatchedUri() string {
	if o == nil || IsNil(o.MatchedUri) {
		var ret string
		return ret
	}
	return *o.MatchedUri
}

// GetMatchedUriOk returns a tuple with the MatchedUri field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1beta1ImportTargetTableInfo) GetMatchedUriOk() (*string, bool) {
	if o == nil || IsNil(o.MatchedUri) {
		return nil, false
	}
	return o.MatchedUri, true
}

// HasMatchedUri returns a boolean if a field has been set.
func (o *V1beta1ImportTargetTableInfo) HasMatchedUri() bool {
	if o != nil && !IsNil(o.MatchedUri) {
		return true
	}

	return false
}

// SetMatchedUri gets a reference to the given string and assigns it to the MatchedUri field.
func (o *V1beta1ImportTargetTableInfo) SetMatchedUri(v string) {
	o.MatchedUri = &v
}

func (o V1beta1ImportTargetTableInfo) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1beta1ImportTargetTableInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TargetTable) {
		toSerialize["targetTable"] = o.TargetTable
	}
	if !IsNil(o.CustomFile) {
		toSerialize["customFile"] = o.CustomFile
	}
	if !IsNil(o.MatchedUri) {
		toSerialize["matchedUri"] = o.MatchedUri
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *V1beta1ImportTargetTableInfo) UnmarshalJSON(data []byte) (err error) {
	varV1beta1ImportTargetTableInfo := _V1beta1ImportTargetTableInfo{}

	err = json.Unmarshal(data, &varV1beta1ImportTargetTableInfo)

	if err != nil {
		return err
	}

	*o = V1beta1ImportTargetTableInfo(varV1beta1ImportTargetTableInfo)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "targetTable")
		delete(additionalProperties, "customFile")
		delete(additionalProperties, "matchedUri")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableV1beta1ImportTargetTableInfo struct {
	value *V1beta1ImportTargetTableInfo
	isSet bool
}

func (v NullableV1beta1ImportTargetTableInfo) Get() *V1beta1ImportTargetTableInfo {
	return v.value
}

func (v *NullableV1beta1ImportTargetTableInfo) Set(val *V1beta1ImportTargetTableInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableV1beta1ImportTargetTableInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableV1beta1ImportTargetTableInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1beta1ImportTargetTableInfo(val *V1beta1ImportTargetTableInfo) *NullableV1beta1ImportTargetTableInfo {
	return &NullableV1beta1ImportTargetTableInfo{value: val, isSet: true}
}

func (v NullableV1beta1ImportTargetTableInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1beta1ImportTargetTableInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
