/*
TiDB Cloud Dedicated Import API

TiDB Cloud Dedicated Import API (subset of the TiDB Cloud Dedicated API, generated from tidbcloud-oas-v1beta1-dedicated.swagger.json)

API version: v1beta1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package imp

import (
	"encoding/json"
)

// checks if the CommonTable type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CommonTable{}

// CommonTable struct for CommonTable
type CommonTable struct {
	// The name of the database containing the target table.
	Schema *string `json:"schema,omitempty"`
	// The name of the table within the database.
	Table                *string `json:"table,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CommonTable CommonTable

// NewCommonTable instantiates a new CommonTable object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCommonTable() *CommonTable {
	this := CommonTable{}
	return &this
}

// NewCommonTableWithDefaults instantiates a new CommonTable object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCommonTableWithDefaults() *CommonTable {
	this := CommonTable{}
	return &this
}

// GetSchema returns the Schema field value if set, zero value otherwise.
func (o *CommonTable) GetSchema() string {
	if o == nil || IsNil(o.Schema) {
		var ret string
		return ret
	}
	return *o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonTable) GetSchemaOk() (*string, bool) {
	if o == nil || IsNil(o.Schema) {
		return nil, false
	}
	return o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *CommonTable) HasSchema() bool {
	if o != nil && !IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given string and assigns it to the Schema field.
func (o *CommonTable) SetSchema(v string) {
	o.Schema = &v
}

// GetTable returns the Table field value if set, zero value otherwise.
func (o *CommonTable) GetTable() string {
	if o == nil || IsNil(o.Table) {
		var ret string
		return ret
	}
	return *o.Table
}

// GetTableOk returns a tuple with the Table field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonTable) GetTableOk() (*string, bool) {
	if o == nil || IsNil(o.Table) {
		return nil, false
	}
	return o.Table, true
}

// HasTable returns a boolean if a field has been set.
func (o *CommonTable) HasTable() bool {
	if o != nil && !IsNil(o.Table) {
		return true
	}

	return false
}

// SetTable gets a reference to the given string and assigns it to the Table field.
func (o *CommonTable) SetTable(v string) {
	o.Table = &v
}

func (o CommonTable) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CommonTable) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Schema) {
		toSerialize["schema"] = o.Schema
	}
	if !IsNil(o.Table) {
		toSerialize["table"] = o.Table
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CommonTable) UnmarshalJSON(data []byte) (err error) {
	varCommonTable := _CommonTable{}

	err = json.Unmarshal(data, &varCommonTable)

	if err != nil {
		return err
	}

	*o = CommonTable(varCommonTable)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "schema")
		delete(additionalProperties, "table")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCommonTable struct {
	value *CommonTable
	isSet bool
}

func (v NullableCommonTable) Get() *CommonTable {
	return v.value
}

func (v *NullableCommonTable) Set(val *CommonTable) {
	v.value = val
	v.isSet = true
}

func (v NullableCommonTable) IsSet() bool {
	return v.isSet
}

func (v *NullableCommonTable) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommonTable(val *CommonTable) *NullableCommonTable {
	return &NullableCommonTable{value: val, isSet: true}
}

func (v NullableCommonTable) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommonTable) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
