/*
TiDB Cloud Dedicated Import API

TiDB Cloud Dedicated Import API (subset of the TiDB Cloud Dedicated API, generated from tidbcloud-oas-v1beta1-dedicated.swagger.json)

API version: v1beta1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package imp

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the V1beta1CreationDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1beta1CreationDetails{}

// V1beta1CreationDetails The details of the import.
type V1beta1CreationDetails struct {
	// The configuration options for the import task.
	ImportOptions V1beta1ImportOptions `json:"importOptions"`
	// The data source for the import task.
	Source V1beta1ImportSource `json:"source"`
	// A list of destination tables and their configurations for the import.
	TargetTableInfos []V1beta1ImportTargetTableInfo `json:"targetTableInfos,omitempty"`
	// A list of validation items that are checked during the import process.
	CheckItems []V1beta1ImportValidationItem `json:"checkItems,omitempty"`
}

type _V1beta1CreationDetails V1beta1CreationDetails

// NewV1beta1CreationDetails instantiates a new V1beta1CreationDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1beta1CreationDetails(importOptions V1beta1ImportOptions, source V1beta1ImportSource) *V1beta1CreationDetails {
	this := V1beta1CreationDetails{}
	this.ImportOptions = importOptions
	this.Source = source
	return &this
}

// NewV1beta1CreationDetailsWithDefaults instantiates a new V1beta1CreationDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1beta1CreationDetailsWithDefaults() *V1beta1CreationDetails {
	this := V1beta1CreationDetails{}
	return &this
}

// GetImportOptions returns the ImportOptions field value
func (o *V1beta1CreationDetails) GetImportOptions() V1beta1ImportOptions {
	if o == nil {
		var ret V1beta1ImportOptions
		return ret
	}

	return o.ImportOptions
}

// GetImportOptionsOk returns a tuple with the ImportOptions field value
// and a boolean to check if the value has been set.
func (o *V1beta1CreationDetails) GetImportOptionsOk() (*V1beta1ImportOptions, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ImportOptions, true
}

// SetImportOptions sets field value
func (o *V1beta1CreationDetails) SetImportOptions(v V1beta1ImportOptions) {
	o.ImportOptions = v
}

// GetSource returns the Source field value
func (o *V1beta1CreationDetails) GetSource() V1beta1ImportSource {
	if o == nil {
		var ret V1beta1ImportSource
		return ret
	}

	return o.Source
}

// GetSourceOk returns a tuple with the Source field value
// and a boolean to check if the value has been set.
func (o *V1beta1CreationDetails) GetSourceOk() (*V1beta1ImportSource, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Source, true
}

// SetSource sets field value
func (o *V1beta1CreationDetails) SetSource(v V1beta1ImportSource) {
	o.Source = v
}

// GetTargetTableInfos returns the TargetTableInfos field value if set, zero value otherwise.
func (o *V1beta1CreationDetails) GetTargetTableInfos() []V1beta1ImportTargetTableInfo {
	if o == nil || IsNil(o.TargetTableInfos) {
		var ret []V1beta1ImportTargetTableInfo
		return ret
	}
	return o.TargetTableInfos
}

// GetTargetTableInfosOk returns a tuple with the TargetTableInfos field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1beta1CreationDetails) GetTargetTableInfosOk() ([]V1beta1ImportTargetTableInfo, bool) {
	if o == nil || IsNil(o.TargetTableInfos) {
		return nil, false
	}
	return o.TargetTableInfos, true
}

// HasTargetTableInfos returns a boolean if a field has been set.
func (o *V1beta1CreationDetails) HasTargetTableInfos() bool {
	if o != nil && !IsNil(o.TargetTableInfos) {
		return true
	}

	return false
}

// SetTargetTableInfos gets a reference to the given []V1beta1ImportTargetTableInfo and assigns it to the TargetTableInfos field.
func (o *V1beta1CreationDetails) SetTargetTableInfos(v []V1beta1ImportTargetTableInfo) {
	o.TargetTableInfos = v
}

// GetCheckItems returns the CheckItems field value if set, zero value otherwise.
func (o *V1beta1CreationDetails) GetCheckItems() []V1beta1ImportValidationItem {
	if o == nil || IsNil(o.CheckItems) {
		var ret []V1beta1ImportValidationItem
		return ret
	}
	return o.CheckItems
}

// GetCheckItemsOk returns a tuple with the CheckItems field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1beta1CreationDetails) GetCheckItemsOk() ([]V1beta1ImportValidationItem, bool) {
	if o == nil || IsNil(o.CheckItems) {
		return nil, false
	}
	return o.CheckItems, true
}

// HasCheckItems returns a boolean if a field has been set.
func (o *V1beta1CreationDetails) HasCheckItems() bool {
	if o != nil && !IsNil(o.CheckItems) {
		return true
	}

	return false
}

// SetCheckItems gets a reference to the given []V1beta1ImportValidationItem and assigns it to the CheckItems field.
func (o *V1beta1CreationDetails) SetCheckItems(v []V1beta1ImportValidationItem) {
	o.CheckItems = v
}

func (o V1beta1CreationDetails) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1beta1CreationDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["importOptions"] = o.ImportOptions
	toSerialize["source"] = o.Source
	if !IsNil(o.TargetTableInfos) {
		toSerialize["targetTableInfos"] = o.TargetTableInfos
	}
	if !IsNil(o.CheckItems) {
		toSerialize["checkItems"] = o.CheckItems
	}
	return toSerialize, nil
}

func (o *V1beta1CreationDetails) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"importOptions",
		"source",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV1beta1CreationDetails := _V1beta1CreationDetails{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV1beta1CreationDetails)

	if err != nil {
		return err
	}

	*o = V1beta1CreationDetails(varV1beta1CreationDetails)

	return err
}

type NullableV1beta1CreationDetails struct {
	value *V1beta1CreationDetails
	isSet bool
}

func (v NullableV1beta1CreationDetails) Get() *V1beta1CreationDetails {
	return v.value
}

func (v *NullableV1beta1CreationDetails) Set(val *V1beta1CreationDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableV1beta1CreationDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableV1beta1CreationDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1beta1CreationDetails(val *V1beta1CreationDetails) *NullableV1beta1CreationDetails {
	return &NullableV1beta1CreationDetails{value: val, isSet: true}
}

func (v NullableV1beta1CreationDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1beta1CreationDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
