/*
TiDB Cloud Dedicated Import API

TiDB Cloud Dedicated Import API (subset of the TiDB Cloud Dedicated API, generated from tidbcloud-oas-v1beta1-dedicated.swagger.json)

API version: v1beta1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package imp

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the V1beta1S3Source type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1beta1S3Source{}

// V1beta1S3Source The S3 source of the import.
type V1beta1S3Source struct {
	// The S3 URI of the import source.
	Uri string `json:"uri"`
	// The authentication method for accessing the S3 bucket.
	AuthType V1beta1ImportS3AuthTypeEnum `json:"authType"`
	// The AWS IAM role ARN used for access. This is required when `authType` is set to `\"ROLE_ARN\"`.
	RoleArn *string `json:"roleArn,omitempty"`
	// The AWS access key credentials used for access. This is required when `authType` is set to `\"ACCESS_KEY\"`.
	AccessKey *S3SourceAccessKey `json:"accessKey,omitempty"`
}

type _V1beta1S3Source V1beta1S3Source

// NewV1beta1S3Source instantiates a new V1beta1S3Source object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1beta1S3Source(uri string, authType V1beta1ImportS3AuthTypeEnum) *V1beta1S3Source {
	this := V1beta1S3Source{}
	this.Uri = uri
	this.AuthType = authType
	return &this
}

// NewV1beta1S3SourceWithDefaults instantiates a new V1beta1S3Source object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1beta1S3SourceWithDefaults() *V1beta1S3Source {
	this := V1beta1S3Source{}
	return &this
}

// GetUri returns the Uri field value
func (o *V1beta1S3Source) GetUri() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uri
}

// GetUriOk returns a tuple with the Uri field value
// and a boolean to check if the value has been set.
func (o *V1beta1S3Source) GetUriOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uri, true
}

// SetUri sets field value
func (o *V1beta1S3Source) SetUri(v string) {
	o.Uri = v
}

// GetAuthType returns the AuthType field value
func (o *V1beta1S3Source) GetAuthType() V1beta1ImportS3AuthTypeEnum {
	if o == nil {
		var ret V1beta1ImportS3AuthTypeEnum
		return ret
	}

	return o.AuthType
}

// GetAuthTypeOk returns a tuple with the AuthType field value
// and a boolean to check if the value has been set.
func (o *V1beta1S3Source) GetAuthTypeOk() (*V1beta1ImportS3AuthTypeEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuthType, true
}

// SetAuthType sets field value
func (o *V1beta1S3Source) SetAuthType(v V1beta1ImportS3AuthTypeEnum) {
	o.AuthType = v
}

// GetRoleArn returns the RoleArn field value if set, zero value otherwise.
func (o *V1beta1S3Source) GetRoleArn() string {
	if o == nil || IsNil(o.RoleArn) {
		var ret string
		return ret
	}
	return *o.RoleArn
}

// GetRoleArnOk returns a tuple with the RoleArn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1beta1S3Source) GetRoleArnOk() (*string, bool) {
	if o == nil || IsNil(o.RoleArn) {
		return nil, false
	}
	return o.RoleArn, true
}

// HasRoleArn returns a boolean if a field has been set.
func (o *V1beta1S3Source) HasRoleArn() bool {
	if o != nil && !IsNil(o.RoleArn) {
		return true
	}

	return false
}

// SetRoleArn gets a reference to the given string and assigns it to the RoleArn field.
func (o *V1beta1S3Source) SetRoleArn(v string) {
	o.RoleArn = &v
}

// GetAccessKey returns the AccessKey field value if set, zero value otherwise.
func (o *V1beta1S3Source) GetAccessKey() S3SourceAccessKey {
	if o == nil || IsNil(o.AccessKey) {
		var ret S3SourceAccessKey
		return ret
	}
	return *o.AccessKey
}

// GetAccessKeyOk returns a tuple with the AccessKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1beta1S3Source) GetAccessKeyOk() (*S3SourceAccessKey, bool) {
	if o == nil || IsNil(o.AccessKey) {
		return nil, false
	}
	return o.AccessKey, true
}

// HasAccessKey returns a boolean if a field has been set.
func (o *V1beta1S3Source) HasAccessKey() bool {
	if o != nil && !IsNil(o.AccessKey) {
		return true
	}

	return false
}

// SetAccessKey gets a reference to the given S3SourceAccessKey and assigns it to the AccessKey field.
func (o *V1beta1S3Source) SetAccessKey(v S3SourceAccessKey) {
	o.AccessKey = &v
}

func (o V1beta1S3Source) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1beta1S3Source) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["uri"] = o.Uri
	toSerialize["authType"] = o.AuthType
	if !IsNil(o.RoleArn) {
		toSerialize["roleArn"] = o.RoleArn
	}
	if !IsNil(o.AccessKey) {
		toSerialize["accessKey"] = o.AccessKey
	}
	return toSerialize, nil
}

func (o *V1beta1S3Source) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"uri",
		"authType",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV1beta1S3Source := _V1beta1S3Source{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV1beta1S3Source)

	if err != nil {
		return err
	}

	*o = V1beta1S3Source(varV1beta1S3Source)

	return err
}

type NullableV1beta1S3Source struct {
	value *V1beta1S3Source
	isSet bool
}

func (v NullableV1beta1S3Source) Get() *V1beta1S3Source {
	return v.value
}

func (v *NullableV1beta1S3Source) Set(val *V1beta1S3Source) {
	v.value = val
	v.isSet = true
}

func (v NullableV1beta1S3Source) IsSet() bool {
	return v.isSet
}

func (v *NullableV1beta1S3Source) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1beta1S3Source(val *V1beta1S3Source) *NullableV1beta1S3Source {
	return &NullableV1beta1S3Source{value: val, isSet: true}
}

func (v NullableV1beta1S3Source) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1beta1S3Source) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
