/*
TiDB Cloud Dedicated Import API

TiDB Cloud Dedicated Import API (subset of the TiDB Cloud Dedicated API, generated from tidbcloud-oas-v1beta1-dedicated.swagger.json)

API version: v1beta1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package imp

import (
	"encoding/json"
	"fmt"
)

// V1beta1ImportStateEnum The state of the import.   - UNSPECIFIED: Indicates that the import state is not specified.  - PREPARING: Indicates that the import is being prepared.  - IMPORTING: Indicates that the import is in progress.  - COMPLETED: Indicates that the import is completed successfully.  - FAILED: Indicates that the import has failed.  - CANCELING: Indicates that the import is in the process of being canceled.  - CANCELED: Indicates that the import has been canceled.
type V1beta1ImportStateEnum string

// List of v1beta1ImportStateEnum
const (
	V1BETA1IMPORTSTATEENUM_UNSPECIFIED V1beta1ImportStateEnum = "UNSPECIFIED"
	V1BETA1IMPORTSTATEENUM_PREPARING   V1beta1ImportStateEnum = "PREPARING"
	V1BETA1IMPORTSTATEENUM_IMPORTING   V1beta1ImportStateEnum = "IMPORTING"
	V1BETA1IMPORTSTATEENUM_COMPLETED   V1beta1ImportStateEnum = "COMPLETED"
	V1BETA1IMPORTSTATEENUM_FAILED      V1beta1ImportStateEnum = "FAILED"
	V1BETA1IMPORTSTATEENUM_CANCELING   V1beta1ImportStateEnum = "CANCELING"
	V1BETA1IMPORTSTATEENUM_CANCELED    V1beta1ImportStateEnum = "CANCELED"
)

// All allowed values of V1beta1ImportStateEnum enum
var AllowedV1beta1ImportStateEnumEnumValues = []V1beta1ImportStateEnum{
	"UNSPECIFIED",
	"PREPARING",
	"IMPORTING",
	"COMPLETED",
	"FAILED",
	"CANCELING",
	"CANCELED",
}

func (v *V1beta1ImportStateEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := V1beta1ImportStateEnum(value)
	for _, existing := range AllowedV1beta1ImportStateEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid V1beta1ImportStateEnum", value)
}

// NewV1beta1ImportStateEnumFromValue returns a pointer to a valid V1beta1ImportStateEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewV1beta1ImportStateEnumFromValue(v string) (*V1beta1ImportStateEnum, error) {
	ev := V1beta1ImportStateEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for V1beta1ImportStateEnum: valid values are %v", v, AllowedV1beta1ImportStateEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v V1beta1ImportStateEnum) IsValid() bool {
	for _, existing := range AllowedV1beta1ImportStateEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to v1beta1ImportStateEnum value
func (v V1beta1ImportStateEnum) Ptr() *V1beta1ImportStateEnum {
	return &v
}

type NullableV1beta1ImportStateEnum struct {
	value *V1beta1ImportStateEnum
	isSet bool
}

func (v NullableV1beta1ImportStateEnum) Get() *V1beta1ImportStateEnum {
	return v.value
}

func (v *NullableV1beta1ImportStateEnum) Set(val *V1beta1ImportStateEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableV1beta1ImportStateEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableV1beta1ImportStateEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1beta1ImportStateEnum(val *V1beta1ImportStateEnum) *NullableV1beta1ImportStateEnum {
	return &NullableV1beta1ImportStateEnum{value: val, isSet: true}
}

func (v NullableV1beta1ImportStateEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1beta1ImportStateEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
